import {
  EntriesNumber,
  IRequestDetails,
  VisaStatus,
  VisaType,
} from "../types/interfaces";

export const allRequests: IRequestDetails[] = [
  {
    id: 1,
    applicationNumber: "1",
    fullName: "Mark Beter",
    visaType: VisaType.Business,
    entriesNumber: EntriesNumber.Single,
    durationOfStay: "14",
    haveapreviousvisa: "No",
    perviousVisaNumber: "---",
    purposeOfVisit: "Attend Meeting",
    passportNumber: "P123456AA",
    currentAddress: "Ottawa, Canada",
    gender: "Female",
    dateOfBirth: "08/01/1990",
    arrivalDate: "12/01/2024",
    departureDate: "12/14/2024",
    mobileNumber: "+1002345678",
    email: "sarah_martin@domain.com",
    emergencyContactName: "Martin Scorsese",
    emergencyContactNumber: "+10023443200",
    status: VisaStatus.Pending,
  },
  {
    id: 2,
    applicationNumber: "2",
    fullName: "James Howard",
    visaType: VisaType.Touristic,
    entriesNumber: EntriesNumber.Double,
    durationOfStay: "30",
    haveapreviousvisa: "Yes",
    perviousVisaNumber: "B56789CD",
    purposeOfVisit: "Vacation",
    passportNumber: "P987654BB",
    currentAddress: "New York, USA",
    gender: "Male",
    dateOfBirth: "05/15/1985",
    arrivalDate: "12/20/2024",
    departureDate: "01/19/2025",
    mobileNumber: "+1019876543",
    email: "james_howard@domain.com",
    emergencyContactName: "Emily Howard",
    emergencyContactNumber: "+1018765432",
    status: VisaStatus.Accepted,
  },
  {
    id: 3,
    applicationNumber: "3",
    fullName: "Sophia Green",
    visaType: VisaType.Business,
    entriesNumber: EntriesNumber.Double,
    durationOfStay: "10",
    haveapreviousvisa: "No",
    perviousVisaNumber: "---",
    purposeOfVisit: "Business Conference",
    passportNumber: "P456789CC",
    currentAddress: "London, UK",
    gender: "Female",
    dateOfBirth: "03/12/1992",
    arrivalDate: "01/10/2024",
    departureDate: "01/20/2024",
    mobileNumber: "+440987654321",
    email: "sophia.green@domain.co.uk",
    emergencyContactName: "Oliver Green",
    emergencyContactNumber: "+440876543210",
    status: VisaStatus.Rejected,
  },
  {
    id: 4,
    applicationNumber: "4",
    fullName: "Liam Brown",
    visaType: VisaType.Touristic,
    entriesNumber: EntriesNumber.Single,
    durationOfStay: "7",
    haveapreviousvisa: "Yes",
    perviousVisaNumber: "A12345EF",
    purposeOfVisit: "Visit Family",
    passportNumber: "P654321DD",
    currentAddress: "Sydney, Australia",
    gender: "Male",
    dateOfBirth: "11/22/1988",
    arrivalDate: "02/01/2024",
    departureDate: "02/08/2024",
    mobileNumber: "+61123456789",
    email: "liam_brown@domain.com.au",
    emergencyContactName: "Emma Brown",
    emergencyContactNumber: "+61198765432",
    status: VisaStatus.Pending,
  },
  {
    id: 5,
    applicationNumber: "5",
    fullName: "Amelia Clarke",
    visaType: VisaType.Business,
    entriesNumber: EntriesNumber.Single,
    durationOfStay: "21",
    haveapreviousvisa: "No",
    perviousVisaNumber: "---",
    purposeOfVisit: "Client Meeting",
    passportNumber: "P123789EE",
    currentAddress: "Toronto, Canada",
    gender: "Female",
    dateOfBirth: "09/05/1994",
    arrivalDate: "01/05/2024",
    departureDate: "01/26/2024",
    mobileNumber: "+1007654321",
    email: "amelia_clarke@domain.ca",
    emergencyContactName: "John Clarke",
    emergencyContactNumber: "+1008765432",
    status: VisaStatus.Accepted,
  },
];
