import {
  EntriesNumber,
  IRequestDetails,
  VisaStatus,
  VisaType,
} from "../types/interfaces";

export const applicantInitialInfo = {
  id: 1,
  applicationNumber: "1",
  fullName: "Mark Beter",
  visaType: VisaType.Business,
  entriesNumber: EntriesNumber.Single,
  durationOfStay: "14",
  haveapreviousvisa: "No",
  perviousVisaNumber: "---",
  purposeOfVisit: "Attend Meeting",
  passportNumber: "P123456AA",
  currentAddress: "Ottawa, Canada",
  gender: "Female",
  dateOfBirth: "08/01/1990",
  arrivalDate: "12/01/2024",
  departureDate: "12/14/2024",
  mobileNumber: "+1002345678",
  email: "sarah_martin@domain.com",
  emergencyContactName: "Martin Scorsese",
  emergencyContactNumber: "+10023443200",
  status: VisaStatus.Pending,
};
export const allRequests: IRequestDetails[] = [
  {
    id: 1,
    applicationNumber: "1",
    fullName: "Mark Beter",
    visaType: VisaType.Business,
    entriesNumber: EntriesNumber.Single,
    durationOfStay: "14",
    haveapreviousvisa: "No",
    perviousVisaNumber: "---",
    purposeOfVisit: "Attend Meeting",
    passportNumber: "P123456AA",
    currentAddress: "Ottawa, Canada",
    gender: "Female",
    dateOfBirth: "08/01/1990",
    arrivalDate: "12/01/2024",
    departureDate: "12/14/2024",
    mobileNumber: "+1002345678",
    email: "sarah_martin@domain.com",
    emergencyContactName: "Martin Scorsese",
    emergencyContactNumber: "+10023443200",
    status: VisaStatus.Pending,
  },
  {
    id: 2,
    applicationNumber: "2",
    fullName: "James Howard",
    visaType: VisaType.Touristic,
    entriesNumber: EntriesNumber.Double,
    durationOfStay: "30",
    haveapreviousvisa: "Yes",
    perviousVisaNumber: "B56789CD",
    purposeOfVisit: "Vacation",
    passportNumber: "P987654BB",
    currentAddress: "New York, USA",
    gender: "Male",
    dateOfBirth: "05/15/1985",
    arrivalDate: "12/20/2024",
    departureDate: "01/19/2025",
    mobileNumber: "+1019876543",
    email: "james_howard@domain.com",
    emergencyContactName: "Emily Howard",
    emergencyContactNumber: "+1018765432",
    status: VisaStatus.Accepted,
  },
  {
    id: 3,
    applicationNumber: "3",
    fullName: "Sophia Green",
    visaType: VisaType.Business,
    entriesNumber: EntriesNumber.Double,
    durationOfStay: "10",
    haveapreviousvisa: "No",
    perviousVisaNumber: "---",
    purposeOfVisit: "Business Conference",
    passportNumber: "P456789CC",
    currentAddress: "London, UK",
    gender: "Female",
    dateOfBirth: "03/12/1992",
    arrivalDate: "01/10/2024",
    departureDate: "01/20/2024",
    mobileNumber: "+440987654321",
    email: "sophia.green@domain.co.uk",
    emergencyContactName: "Oliver Green",
    emergencyContactNumber: "+440876543210",
    status: VisaStatus.Rejected,
  },
  {
    id: 4,
    applicationNumber: "4",
    fullName: "Liam Brown",
    visaType: VisaType.Touristic,
    entriesNumber: EntriesNumber.Single,
    durationOfStay: "7",
    haveapreviousvisa: "Yes",
    perviousVisaNumber: "A12345EF",
    purposeOfVisit: "Visit Family",
    passportNumber: "P654321DD",
    currentAddress: "Sydney, Australia",
    gender: "Male",
    dateOfBirth: "11/22/1988",
    arrivalDate: "02/01/2024",
    departureDate: "02/08/2024",
    mobileNumber: "+61123456789",
    email: "liam_brown@domain.com.au",
    emergencyContactName: "Emma Brown",
    emergencyContactNumber: "+61198765432",
    status: VisaStatus.Pending,
  },
  {
    id: 5,
    applicationNumber: "5",
    fullName: "Amelia Clarke",
    visaType: VisaType.Business,
    entriesNumber: EntriesNumber.Single,
    durationOfStay: "21",
    haveapreviousvisa: "No",
    perviousVisaNumber: "---",
    purposeOfVisit: "Client Meeting",
    passportNumber: "P123789EE",
    currentAddress: "Toronto, Canada",
    gender: "Female",
    dateOfBirth: "09/05/1994",
    arrivalDate: "01/05/2024",
    departureDate: "01/26/2024",
    mobileNumber: "+1007654321",
    email: "amelia_clarke@domain.ca",
    emergencyContactName: "John Clarke",
    emergencyContactNumber: "+1008765432",
    status: VisaStatus.Accepted,
  },
];

export const countries = [
  { id: 1, value: "United States" },
  { id: 2, value: "United Kingdom" },
  { id: 3, value: "Afghanistan" },
  { id: 4, value: "Albania" },
  { id: 5, value: "Algeria" },
  { id: 6, value: "American Samoa" },
  { id: 7, value: "Andorra" },
  { id: 8, value: "Angola" },
  { id: 9, value: "Anguilla" },
  { id: 10, value: "Antarctica" },
  { id: 11, value: "Antigua and Barbuda" },
  { id: 12, value: "Argentina" },
  { id: 13, value: "Armenia" },
  { id: 14, value: "Aruba" },
  { id: 15, value: "Australia" },
  { id: 16, value: "Austria" },
  { id: 17, value: "Azerbaijan" },
  { id: 18, value: "Bahamas" },
  { id: 19, value: "Bahrain" },
  { id: 20, value: "Bangladesh" },
  { id: 21, value: "Barbados" },
  { id: 22, value: "Belarus" },
  { id: 23, value: "Belgium" },
  { id: 24, value: "Belize" },
  { id: 25, value: "Benin" },
  { id: 26, value: "Bermuda" },
  { id: 27, value: "Bhutan" },
  { id: 28, value: "Bolivia" },
  { id: 29, value: "Bosnia and Herzegovina" },
  { id: 30, value: "Botswana" },
  { id: 31, value: "Bouvet Island" },
  { id: 32, value: "Brazil" },
  { id: 33, value: "British Indian Ocean Territory" },
  { id: 34, value: "Brunei Darussalam" },
  { id: 35, value: "Bulgaria" },
  { id: 36, value: "Burkina Faso" },
  { id: 37, value: "Burundi" },
  { id: 38, value: "Cambodia" },
  { id: 39, value: "Cameroon" },
  { id: 40, value: "Canada" },
  { id: 41, value: "Cape Verde" },
  { id: 42, value: "Cayman Islands" },
  { id: 43, value: "Central African Republic" },
  { id: 44, value: "Chad" },
  { id: 45, value: "Chile" },
  { id: 46, value: "China" },
  { id: 47, value: "Christmas Island" },
  { id: 48, value: "Cocos (Keeling) Islands" },
  { id: 49, value: "Colombia" },
  { id: 50, value: "Comoros" },
  { id: 51, value: "Congo" },
  { id: 52, value: "Congo, The Democratic Republic of the" },
  { id: 53, value: "Cook Islands" },
  { id: 54, value: "Costa Rica" },
  { id: 55, value: "Cote D'Ivoire" },
  { id: 56, value: "Croatia" },
  { id: 57, value: "Cuba" },
  { id: 58, value: "Cyprus" },
  { id: 59, value: "Czech Republic" },
  { id: 60, value: "Denmark" },
  { id: 61, value: "Djibouti" },
  { id: 62, value: "Dominica" },
  { id: 63, value: "Dominican Republic" },
  { id: 64, value: "Ecuador" },
  { id: 65, value: "Egypt" },
  { id: 66, value: "El Salvador" },
  { id: 67, value: "Equatorial Guinea" },
  { id: 68, value: "Eritrea" },
  { id: 69, value: "Estonia" },
  { id: 70, value: "Ethiopia" },
  { id: 71, value: "Falkland Islands (Malvinas)" },
  { id: 72, value: "Faroe Islands" },
  { id: 73, value: "Fiji" },
  { id: 74, value: "Finland" },
  { id: 75, value: "France" },
  { id: 76, value: "French Guiana" },
  { id: 77, value: "French Polynesia" },
  { id: 78, value: "French Southern Territories" },
  { id: 79, value: "Gabon" },
  { id: 80, value: "Gambia" },
  { id: 81, value: "Georgia" },
  { id: 82, value: "Germany" },
  { id: 83, value: "Ghana" },
  { id: 84, value: "Gibraltar" },
  { id: 85, value: "Greece" },
  { id: 86, value: "Greenland" },
  { id: 87, value: "Grenada" },
  { id: 88, value: "Guadeloupe" },
  { id: 89, value: "Guam" },
  { id: 90, value: "Guatemala" },
  { id: 91, value: "Guinea" },
  { id: 92, value: "Guinea-Bissau" },
  { id: 93, value: "Guyana" },
  { id: 94, value: "Haiti" },
  { id: 95, value: "Heard Island and Mcdonald Islands" },
  { id: 96, value: "Holy See (Vatican City State)" },
  { id: 97, value: "Honduras" },
  { id: 98, value: "Hong Kong" },
  { id: 99, value: "Hungary" },
  { id: 100, value: "Iceland" },
  { id: 101, value: "India" },
  { id: 102, value: "Indonesia" },
  { id: 103, value: "Iran, Islamic Republic of" },
  { id: 104, value: "Iraq" },
  { id: 105, value: "Ireland" },
  { id: 106, value: "Israel" },
  { id: 107, value: "Italy" },
  { id: 108, value: "Jamaica" },
  { id: 109, value: "Japan" },
  { id: 110, value: "Jordan" },
  { id: 111, value: "Kazakhstan" },
  { id: 112, value: "Kenya" },
  { id: 113, value: "Kiribati" },
  { id: 114, value: "Korea, Democratic People's Republic of" },
  { id: 115, value: "Korea, Republic of" },
  { id: 116, value: "Kuwait" },
  { id: 117, value: "Kyrgyzstan" },
  { id: 118, value: "Lao People's Democratic Republic" },
  { id: 119, value: "Latvia" },
  { id: 120, value: "Lebanon" },
  { id: 121, value: "Lesotho" },
  { id: 122, value: "Liberia" },
  { id: 123, value: "Libyan Arab Jamahiriya" },
  { id: 124, value: "Liechtenstein" },
  { id: 125, value: "Lithuania" },
  { id: 126, value: "Luxembourg" },
  { id: 127, value: "Macao" },
  { id: 128, value: "Macedonia, The Former Yugoslav Republic of" },
  { id: 129, value: "Madagascar" },
  { id: 130, value: "Malawi" },
  { id: 131, value: "Malaysia" },
  { id: 132, value: "Maldives" },
  { id: 133, value: "Mali" },
  { id: 134, value: "Malta" },
  { id: 135, value: "Marshall Islands" },
  { id: 136, value: "Martinique" },
  { id: 137, value: "Mauritania" },
  { id: 138, value: "Mauritius" },
  { id: 139, value: "Mayotte" },
  { id: 140, value: "Mexico" },
  { id: 141, value: "Micronesia, Federated States of" },
  { id: 142, value: "Moldova, Republic of" },
  { id: 143, value: "Monaco" },
  { id: 144, value: "Mongolia" },
  { id: 145, value: "Montenegro" },
  { id: 146, value: "Montserrat" },
  { id: 147, value: "Morocco" },
  { id: 148, value: "Mozambique" },
  { id: 149, value: "Myanmar" },
  { id: 150, value: "Namibia" },
  { id: 151, value: "Nauru" },
  { id: 152, value: "Nepal" },
  { id: 153, value: "Netherlands" },
  { id: 154, value: "New Caledonia" },
  { id: 155, value: "New Zealand" },
  { id: 156, value: "Nicaragua" },
  { id: 157, value: "Niger" },
  { id: 158, value: "Nigeria" },
  { id: 159, value: "Niue" },
  { id: 160, value: "Norfolk Island" },
  { id: 161, value: "Northern Mariana Islands" },
  { id: 162, value: "Norway" },
  { id: 163, value: "Oman" },
  { id: 164, value: "Pakistan" },
  { id: 165, value: "Palau" },
  { id: 166, value: "Palestinian Territory, Occupied" },
  { id: 167, value: "Panama" },
  { id: 168, value: "Papua New Guinea" },
  { id: 169, value: "Paraguay" },
  { id: 170, value: "Peru" },
  { id: 171, value: "Philippines" },
  { id: 172, value: "Pitcairn" },
  { id: 173, value: "Poland" },
  { id: 174, value: "Portugal" },
  { id: 175, value: "Puerto Rico" },
  { id: 176, value: "Qatar" },
  { id: 177, value: "Reunion" },
  { id: 178, value: "Romania" },
  { id: 179, value: "Russian Federation" },
  { id: 180, value: "Rwanda" },
  { id: 181, value: "Saint Helena" },
  { id: 182, value: "Saint Kitts and Nevis" },
  { id: 183, value: "Saint Lucia" },
  { id: 184, value: "Saint Pierre and Miquelon" },
  { id: 185, value: "Saint Vincent and the Grenadines" },
  { id: 186, value: "Samoa" },
  { id: 187, value: "San Marino" },
  { id: 188, value: "Sao Tome and Principe" },
  { id: 189, value: "Saudi Arabia" },
  { id: 190, value: "Senegal" },
  { id: 191, value: "Serbia" },
  { id: 192, value: "Seychelles" },
  { id: 193, value: "Sierra Leone" },
  { id: 194, value: "Singapore" },
  { id: 195, value: "Slovakia" },
  { id: 196, value: "Slovenia" },
  { id: 197, value: "Solomon Islands" },
  { id: 198, value: "Somalia" },
  { id: 199, value: "South Africa" },
  { id: 200, value: "South Georgia and the South Sandwich Islands" },
  { id: 201, value: "Spain" },
  { id: 202, value: "Sri Lanka" },
  { id: 203, value: "Sudan" },
  { id: 204, value: "Suriname" },
  { id: 205, value: "Svalbard and Jan Mayen" },
  { id: 206, value: "Swaziland" },
  { id: 207, value: "Sweden" },
  { id: 208, value: "Switzerland" },
  { id: 209, value: "Syrian Arab Republic" },
  { id: 210, value: "Taiwan, Province of China" },
  { id: 211, value: "Tajikistan" },
  { id: 212, value: "Tanzania, United Republic of" },
  { id: 213, value: "Thailand" },
  { id: 214, value: "Timor-Leste" },
  { id: 215, value: "Togo" },
  { id: 216, value: "Tokelau" },
  { id: 217, value: "Tonga" },
  { id: 218, value: "Trinidad and Tobago" },
  { id: 219, value: "Tunisia" },
  { id: 220, value: "Turkey" },
  { id: 221, value: "Turkmenistan" },
  { id: 222, value: "Turks and Caicos Islands" },
  { id: 223, value: "Tuvalu" },
  { id: 224, value: "Uganda" },
  { id: 225, value: "Ukraine" },
  { id: 226, value: "United Arab Emirates" },
  { id: 227, value: "United States Minor Outlying Islands" },
  { id: 228, value: "Uruguay" },
  { id: 229, value: "Uzbekistan" },
  { id: 230, value: "Vanuatu" },
  { id: 231, value: "Venezuela" },
  { id: 232, value: "Viet Nam" },
  { id: 233, value: "Virgin Islands, British" },
  { id: 234, value: "Virgin Islands, U.S." },
  { id: 235, value: "Wallis and Futuna" },
  { id: 236, value: "Western Sahara" },
  { id: 237, value: "Yemen" },
  { id: 238, value: "Zambia" },
  { id: 239, value: "Zimbabwe" },
];
